language: c
compiler: gcc

before_install:
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install:
- sudo apt-get install cmake
- sudo apt-get install libevent-dev
- sudo apt-get install libmosquitto-dev
- sudo apt-get install libcurl-dev
- sudo apt-get install libmariadbclient-dev

script:
- make

# whitelist
branches:
  only:
    - master
    - dev
    - travis

