language: c
compiler: gcc

env:
    - BUILD_TYPE=Release

before_install:
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install:
- sudo apt-get install cmake
- sudo apt-get install libevent-dev
- sudo apt-get install mosquitto
- sudo apt-get install libcurl-dev
- sudo apt-get install libmariadbclient-dev

- wget https://github.com/downloads/HardySimpson/zlog/zlog-latest-stable.tar.gz
- tar -zxvf zlog-latest-stable.tar.gz
- cd zlog-latest-stable/
- ./configure
- make
- sudo make install
- cd ..

- wget http://github.com/yunba/yunba-c-sdk/archive/develop.zip
- unzip yunba-c-sdk-develop.zip
- cd yunba-c-sdk-develop/
- make
- sudo make install
- cd ..

script:
- make
#- cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

# whitelist
branches:
  only:
    - master
    - dev
    - travis

