language: c
compiler: gcc

env:
    - BUILD_TYPE=Release

before_install:
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install:
- sudo apt-get install cmake
- sudo apt-get install libevent-dev
#- wget https://sourceforge.net/projects/levent/files/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz
#- tar zxf libevent-2.0.22-stable.tar.gz
#- cd libevent-2.0.22-stable
- sudo apt-get install libmosquitto0-dev

#- sudo apt-get install libcurl4-openssl-dev


- sudo apt-get install libmysqlclient-dev

#- wget https://github.com/downloads/HardySimpson/zlog/zlog-latest-stable.tar.gz
#- tar -zxvf zlog-latest-stable.tar.gz
#- cd zlog-latest-stable/
- git clone https://github.com/HardySimpson/zlog.git
- cd zlog && make && sudo make install


#- wget http://github.com/yunba/yunba-c-sdk/archive/develop.zip
#- unzip yunba-c-sdk-develop.zip
#- cd yunba-c-sdk-develop/
- git clone https://github.com/yunba/yunba-c-sdk.git
- cd yunba-c-sdk && git checkout develop
- make && sudo make install
- cd ..

before_script:
- ls -R $HOME

script:
- cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

# whitelist
branches:
  only:
    - master
    - dev
    - travis

